title: Kernel Panic!!
description: All about Linux kernel, RISC-V and system issues.
author: Atish Patra
github: https://github.com/atishp04
about: I am Linux kernel developer. Currently contributing to RISC-V and other core kernel components.
disqus_shortname: kerneltalks
avatar_url: /static/img/profile.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/atishp04"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/atishpatra"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/atishp04"

share:
  twitter_username: atishp04

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

#url: https://atishp04.github.io/test
#baseurl: /test/

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://atishp04.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"


paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
